### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Magdalena-Szeremet** [appioframework/APPIOframework#3]
- No description for -t option of appio inport command in online documentation: https://appioframework.readthedocs.io/en/latest/import.html. This option is used while importing information models in Pump Example to import DiTypes.bsd file.
- Misleading description of appio version command usage. It suggest caling it like 'appio --version'.
- No example of using -s option for importing information models in online documentation. No information about available samples.

**Comment by appioframework** [comment]
Option -t for appio import will be removed in release v1.0.0.
